### ISSUE TITLE
Segfault under Weston on Fedora 32

### ISSUE THREAD

**Issue by gergelypolonkai** [eXeC64/imv#263]
I’m temporarily running weston on my F32 box and tried to open an image with `imv` (installed from the official repos). It runs fine under Sway, but segfaults on weston.

**Comment by alebastr** [comment]
Problem started around here:
https://github.com/eXeC64/imv/blob/a222f6475b905bdd0f55752e1539ed17bcad0a77/src/wl_window.c#L106-L108

`mmap` always fails with `EPERM` on weston, but not on sway ¯\\\_(ツ)\_/¯

Might be specific for Fedora, but I don't have other distros to check.
Weston: 8.0.0-4.fc32.x86_64
imv: 4.1.0, git master
```
#0  0x00007fb8848cc557 in __strlen_avx2 () at /lib64/libc.so.6
#1  0x00007fb887aea011 in xkb_keymap_new_from_string
    (ctx=0x55d29f74bca0, string=string@entry=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, format=format@entry=XKB_KEYMAP_FORMAT_TEXT_V1, flags=flags@entry=XKB_KEYMAP_COMPILE_NO_FLAGS) at ../src/keymap.c:164
#2  0x000055d29f2a285b in imv_keyboard_set_keymap (keyboard=0x55d29f74bc80, keymap=keymap@entry=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>)
    at src/keyboard.c:129
#3  0x000055d29f2a523f in keyboard_keymap (data=0x55d29f74bb80, keyboard=<optimized out>, format=<optimized out>, fd=12, size=47298) at src/wl_window.c:107
#4  0x00007fb884484af0 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#5  0x00007fb8844842ab in ffi_call (cif=cif@entry=0x7ffc3db8b500, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7ffc3db8b5d0) at ../src/x86/ffi64.c:525
#6  0x00007fb8849657e2 in wl_closure_invoke (closure=0x55d29f785270, flags=1, target=<optimized out>, opcode=0, data=<optimized out>) at src/connection.c:1018
#7  0x00007fb884961dba in dispatch_event (display=display@entry=0x55d29f7667b0, queue=0x55d29f766880, queue=<optimized out>) at src/wayland-client.c:1445
#8  0x00007fb8849634ac in dispatch_queue (queue=0x55d29f766880, display=0x55d29f7667b0) at src/wayland-client.c:1591
#9  wl_display_dispatch_queue_pending (display=0x55d29f7667b0, queue=0x55d29f766880) at src/wayland-client.c:1833
#10 0x00007fb8849639af in wl_display_roundtrip_queue (display=0x55d29f7667b0, queue=0x55d29f766880) at src/wayland-client.c:1251
#11 0x00007fb8849639f0 in wl_display_roundtrip (display=<optimized out>) at src/wayland-client.c:1280
#12 0x000055d29f2a604a in create_window (title=0x55d29f2a75d0 "imv", height=720, width=1280, window=0x55d29f74bb80) at src/wl_window.c:706
#13 imv_window_create (width=1280, height=720, title=title@entry=0x55d29f2a75d0 "imv") at src/wl_window.c:767
#14 0x000055d29f2a13b5 in setup_window (imv=0x55d29f740830) at src/imv.c:1051
#15 imv_run (imv=0x55d29f740830) at src/imv.c:833
#16 0x000055d29f29caeb in main (argc=2, argv=0x7ffc3db8c218) at src/main.c:54
```
